### ISSUE TITLE
Only maintain our custom changes

### ISSUE THREAD

**Issue by ramasilveyra** [auth0/javascript#12]
We should only make a eslint extend from airbnb and only maintain our custom changes
eg for `eslint-config-airbnb-base`:

``` javascript
module.exports = {
  extends: [
    'eslint-config-airbnb-base',
    './rules/error' // only our custom rules error changes
    './rules/es6' // only our custom rule es6 changes
  ].map(require.resolve),
  rules: {}
};
```

This is to make this fork more easy to maintain and keep up to date.

**Comment by fiddur** [comment]
Sounds good; and the readme should state that it is a modified version of airbnb with a list of the alterations.
